// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkEQm2xEgZlus5sEH7x4IA2pwCh9B6N-o',
    appId: '1:1097717413230:web:bf034670ef952a134c7d7f',
    messagingSenderId: '1097717413230',
    projectId: 'fir-wallpaper-app-afcba',
    authDomain: 'fir-wallpaper-app-afcba.firebaseapp.com',
    storageBucket: 'fir-wallpaper-app-afcba.firebasestorage.app',
    measurementId: 'G-Q456M4FB9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlV7taGNOY3pn8a0Sfj5ZBg1Y1rS5yA3Q',
    appId: '1:1097717413230:android:dcfa2c9a2a8437774c7d7f',
    messagingSenderId: '1097717413230',
    projectId: 'fir-wallpaper-app-afcba',
    storageBucket: 'fir-wallpaper-app-afcba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy8E9idJuMOz4CEddhCW_UvmKX0dYes-E',
    appId: '1:1097717413230:ios:edf131c56cbeef954c7d7f',
    messagingSenderId: '1097717413230',
    projectId: 'fir-wallpaper-app-afcba',
    storageBucket: 'fir-wallpaper-app-afcba.firebasestorage.app',
    iosBundleId: 'com.example.firebaseWallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy8E9idJuMOz4CEddhCW_UvmKX0dYes-E',
    appId: '1:1097717413230:ios:edf131c56cbeef954c7d7f',
    messagingSenderId: '1097717413230',
    projectId: 'fir-wallpaper-app-afcba',
    storageBucket: 'fir-wallpaper-app-afcba.firebasestorage.app',
    iosBundleId: 'com.example.firebaseWallpaperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkEQm2xEgZlus5sEH7x4IA2pwCh9B6N-o',
    appId: '1:1097717413230:web:ef47b3fd93ea2b904c7d7f',
    messagingSenderId: '1097717413230',
    projectId: 'fir-wallpaper-app-afcba',
    authDomain: 'fir-wallpaper-app-afcba.firebaseapp.com',
    storageBucket: 'fir-wallpaper-app-afcba.firebasestorage.app',
    measurementId: 'G-HJ0KTZYH4R',
  );
}
