// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBso32szUgIk350n2smOPMlk5KxVAMNtxw',
    appId: '1:561227410931:web:4e21c4c3c14ffe93793686',
    messagingSenderId: '561227410931',
    projectId: 'fir-demo-a84e9',
    authDomain: 'fir-demo-a84e9.firebaseapp.com',
    storageBucket: 'fir-demo-a84e9.firebasestorage.app',
    measurementId: 'G-E4ZQRQKJTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTB3OkQ4AXAqnH_THvwkZFWF1v9JYrzE',
    appId: '1:561227410931:android:b10bbc4db3613c89793686',
    messagingSenderId: '561227410931',
    projectId: 'fir-demo-a84e9',
    storageBucket: 'fir-demo-a84e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5gxFzCVlGaAEFoCJfFv9vCYBo_BHzbpk',
    appId: '1:561227410931:ios:aa4c420a5a0c88c5793686',
    messagingSenderId: '561227410931',
    projectId: 'fir-demo-a84e9',
    storageBucket: 'fir-demo-a84e9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5gxFzCVlGaAEFoCJfFv9vCYBo_BHzbpk',
    appId: '1:561227410931:ios:aa4c420a5a0c88c5793686',
    messagingSenderId: '561227410931',
    projectId: 'fir-demo-a84e9',
    storageBucket: 'fir-demo-a84e9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBso32szUgIk350n2smOPMlk5KxVAMNtxw',
    appId: '1:561227410931:web:1d3f7c5108abd439793686',
    messagingSenderId: '561227410931',
    projectId: 'fir-demo-a84e9',
    authDomain: 'fir-demo-a84e9.firebaseapp.com',
    storageBucket: 'fir-demo-a84e9.firebasestorage.app',
    measurementId: 'G-HHP26F9YJY',
  );
}
